# Generated by Django 2.2.6 on 2019-12-18 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_note', models.TextField(max_length=500)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Note')),
            ],
        ),
    ]
