# Generated by Django 2.2.6 on 2019-12-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('U', 'Urgent'), ('A', 'About time'), ('C', 'chill')], default='A', max_length=3),
        ),
    ]
